CREATE DATABASE Escola;

USE Escola;

CREATE TABLE alunos(
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL,
notas DECIMAL,
turma VARCHAR(50) NOT NULL
);

ALTER TABLE Alunos RENAME TO alunos;
ALTER TABLE alunos ADD COLUMN email VARCHAR(50);

SELECT * FROM alunos;

DROP TABLE alunos;

DROP DATABASE Escola;


